server:
  port: 8080
spring:
  application:
    name: analysis
  datasource: #数据源
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/analysis?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    #模板的模式 支持html xml text JavaScript
    mode: HTML5
    #编码格式 utf-8 可以不用配置
    encoding: UTF-8
    #容器类型 可以不用配置
    content-type: text/html
    #开发时置为false 避免修改模板还要重启
    cache: false
    #默认模板配置路径 默认就是templates 可以不用配置
    prefix: classpath:/templates


mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  # 配置类型别名
  #type-aliases-package: com.guoxi.*.*
  #mybatis配置
  #config: classpath:mybatis.xml